package com.example.orderprocessing.property.pricing;

import com.example.orderprocessing.domain.model.Money;
import com.example.orderprocessing.domain.model.Order;
import com.example.orderprocessing.domain.model.OrderBuilder;
import com.example.orderprocessing.domain.model.OrderId;
import com.example.orderprocessing.domain.model.OrderItem;
import com.example.orderprocessing.domain.model.OrderStatus;
import com.example.orderprocessing.domain.model.Sku;
import com.example.orderprocessing.domain.pricing.PricingEngine;
import com.example.orderprocessing.domain.pricing.PricingStrategyChainFactory;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Property-based tests for idempotent chain stability.
 *
 * <p>Validates that when every strategy in the chain declares {@code isIdempotent()},
 * applying the chain twice to the same order yields the same grand total as applying
 * it once.
 */
class IdempotentChainStabilityProperties {

    private static final Currency USD = Currency.getInstance("USD");
    private static final PricingEngine ENGINE =
            new PricingEngine(new PricingStrategyChainFactory());

    /**
     * Provides an arbitrary unit price amount between 0.01 and 9999.99 (scale ≤ 2).
     *
     * @return arbitrary {@link BigDecimal} suitable for a unit price
     */
    @Provide
    Arbitrary<BigDecimal> unitPriceAmount() {
        return Arbitraries.bigDecimals()
                .between(new BigDecimal("0.01"), new BigDecimal("9999.99"))
                .ofScale(2);
    }

    /**
     * Provides an arbitrary supported pricing profile name where all strategies are idempotent.
     *
     * <p>Both {@code "default"} and {@code "no-op"} profiles consist entirely of strategies
     * that declare {@code isIdempotent() == true} (DiscountStrategy, TaxStrategy,
     * ShippingStrategy, and NoOpStrategy all return {@code true}).
     *
     * @return arbitrary over idempotent profile names
     */
    @Provide
    Arbitrary<String> idempotentProfile() {
        return Arbitraries.of("default", "no-op");
    }

    /**
     * Property 6: When every strategy declares isIdempotent(), applying the chain twice
     * yields the same grandTotal as applying it once.
     *
     * <p>The second application re-prices the already-priced order using the same profile.
     * Because all strategies in the supported profiles are idempotent (they compute their
     * contribution from the original item prices, not from accumulated totals), the grand
     * total must be identical after both applications.
     *
     * <p><b>Validates: Requirements 20.3</b>
     *
     * @param unitPrice the unit price amount generated by jqwik
     * @param quantity  the item quantity generated by jqwik
     * @param profile   the idempotent pricing profile name generated by jqwik
     */
    @Property
    void idempotentChainAppliedTwiceYieldsSameGrandTotal(
            @ForAll("unitPriceAmount") BigDecimal unitPrice,
            @ForAll @IntRange(min = 1, max = 100) int quantity,
            @ForAll("idempotentProfile") String profile) {

        Order order = buildValidatedOrder(unitPrice, quantity);

        // First application: VALIDATED → PRICED
        Order pricedOnce = ENGINE.price(order, profile);

        // Second application: re-price the already-priced order using the same profile.
        // The engine does not enforce VALIDATED status, so we re-price from the priced order.
        Order pricedTwice = ENGINE.price(pricedOnce.withStatus(OrderStatus.VALIDATED), profile);

        assertEquals(
                0,
                pricedOnce.getGrandTotal().amount().compareTo(pricedTwice.getGrandTotal().amount()),
                () -> String.format(
                        "Idempotent chain stability violated for profile='%s', unitPrice=%s, qty=%d: "
                        + "first application grandTotal=%s, second application grandTotal=%s",
                        profile, unitPrice, quantity,
                        pricedOnce.getGrandTotal().amount(),
                        pricedTwice.getGrandTotal().amount()));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Builds a minimal {@link Order} in {@link OrderStatus#VALIDATED} status with one item.
     *
     * @param unitPrice the unit price amount for the single item
     * @param quantity  the item quantity
     * @return a valid order ready to be priced
     */
    private Order buildValidatedOrder(BigDecimal unitPrice, int quantity) {
        Money price = Money.of(unitPrice, USD);
        OrderItem item = new OrderItem(new Sku("SKU-001"), quantity, price);
        return new OrderBuilder()
                .id(new OrderId(UUID.randomUUID()))
                .item(item)
                .status(OrderStatus.VALIDATED)
                .currency(USD)
                .build();
    }
}
