package com.example.orderprocessing.property.pricing;

import com.example.orderprocessing.domain.model.Money;
import com.example.orderprocessing.domain.model.Order;
import com.example.orderprocessing.domain.model.OrderBuilder;
import com.example.orderprocessing.domain.model.OrderId;
import com.example.orderprocessing.domain.model.OrderItem;
import com.example.orderprocessing.domain.model.OrderStatus;
import com.example.orderprocessing.domain.model.Sku;
import com.example.orderprocessing.domain.pricing.PricingEngine;
import com.example.orderprocessing.domain.pricing.PricingStrategyChainFactory;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Property-based tests for the no-op chain identity invariant.
 *
 * <p>Validates that applying a chain consisting entirely of
 * {@link com.example.orderprocessing.domain.pricing.strategies.NoOpStrategy} instances
 * yields a grand total equal to the order subtotal.
 */
class NoOpChainIdentityProperties {

    private static final Currency USD = Currency.getInstance("USD");
    private static final PricingEngine ENGINE =
            new PricingEngine(new PricingStrategyChainFactory());

    /**
     * Provides an arbitrary unit price amount between 0.01 and 9999.99 (scale ≤ 2).
     *
     * @return arbitrary {@link BigDecimal} suitable for a unit price
     */
    @Provide
    Arbitrary<BigDecimal> unitPriceAmount() {
        return Arbitraries.bigDecimals()
                .between(new BigDecimal("0.01"), new BigDecimal("9999.99"))
                .ofScale(2);
    }

    /**
     * Property 5: Applying a chain of only NoOpStrategy yields grandTotal == subtotal.
     *
     * <p>When the pricing profile is {@code "no-op"}, the strategy chain contains only
     * {@link com.example.orderprocessing.domain.pricing.strategies.NoOpStrategy} instances.
     * Each contributes zero discount, zero tax, and zero shipping, so the grand total must
     * equal the computed subtotal exactly.
     *
     * <p><b>Validates: Requirements 20.2</b>
     *
     * @param unitPrice the unit price amount generated by jqwik
     * @param quantity  the item quantity generated by jqwik
     */
    @Property
    void noOpChainYieldsGrandTotalEqualToSubtotal(
            @ForAll("unitPriceAmount") BigDecimal unitPrice,
            @ForAll @IntRange(min = 1, max = 100) int quantity) {

        Order order = buildValidatedOrder(unitPrice, quantity);
        Order priced = ENGINE.price(order, "no-op");

        assertEquals(
                0,
                priced.getSubtotal().amount().compareTo(priced.getGrandTotal().amount()),
                () -> String.format(
                        "no-op chain identity violated: subtotal=%s but grandTotal=%s "
                        + "(unitPrice=%s, qty=%d)",
                        priced.getSubtotal().amount(), priced.getGrandTotal().amount(),
                        unitPrice, quantity));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Builds a minimal {@link Order} in {@link OrderStatus#VALIDATED} status with one item.
     *
     * @param unitPrice the unit price amount for the single item
     * @param quantity  the item quantity
     * @return a valid order ready to be priced
     */
    private Order buildValidatedOrder(BigDecimal unitPrice, int quantity) {
        Money price = Money.of(unitPrice, USD);
        OrderItem item = new OrderItem(new Sku("SKU-001"), quantity, price);
        return new OrderBuilder()
                .id(new OrderId(UUID.randomUUID()))
                .item(item)
                .status(OrderStatus.VALIDATED)
                .currency(USD)
                .build();
    }
}
