package com.example.orderprocessing.property.pricing;

import com.example.orderprocessing.domain.model.Money;
import com.example.orderprocessing.domain.model.Order;
import com.example.orderprocessing.domain.model.OrderBuilder;
import com.example.orderprocessing.domain.model.OrderId;
import com.example.orderprocessing.domain.model.OrderItem;
import com.example.orderprocessing.domain.model.OrderStatus;
import com.example.orderprocessing.domain.model.Sku;
import com.example.orderprocessing.domain.pricing.PricingEngine;
import com.example.orderprocessing.domain.pricing.PricingStrategyChainFactory;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;
import net.jqwik.api.constraints.Scale;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Property-based tests for the pricing grand-total invariant.
 *
 * <p>Validates that the {@link PricingEngine} always satisfies:
 * {@code grandTotal = subtotal - discountTotal + taxTotal + shippingTotal}
 * for any valid order and any supported pricing profile.
 */
class PricingTotalInvariantProperties {

    private static final Currency USD = Currency.getInstance("USD");
    private static final PricingEngine ENGINE =
            new PricingEngine(new PricingStrategyChainFactory());

    /**
     * Provides an arbitrary unit price amount between 0.01 and 999.99 (scale ≤ 2).
     *
     * @return arbitrary {@link BigDecimal} suitable for a unit price
     */
    @Provide
    Arbitrary<BigDecimal> unitPriceAmount() {
        return Arbitraries.bigDecimals()
                .between(new BigDecimal("0.01"), new BigDecimal("999.99"))
                .ofScale(2);
    }

    /**
     * Provides an arbitrary supported pricing profile name.
     *
     * @return arbitrary over the supported profile names
     */
    @Provide
    Arbitrary<String> supportedProfile() {
        return Arbitraries.of("default", "no-op");
    }

    /**
     * Property 3: grand_total = subtotal - discountTotal + taxTotal + shippingTotal.
     *
     * <p>For any valid order and any supported pricing profile, the grand total computed
     * by the {@link PricingEngine} must equal the arithmetic combination of the other
     * four totals stored on the resulting priced order.
     *
     * <p><b>Validates: Requirements 3.4</b>
     *
     * @param unitPrice the unit price amount generated by jqwik
     * @param quantity  the item quantity generated by jqwik
     * @param profile   the pricing profile name generated by jqwik
     */
    @Property
    void grandTotalEqualsSubtotalMinusDiscountPlusTaxPlusShipping(
            @ForAll("unitPriceAmount") BigDecimal unitPrice,
            @ForAll @IntRange(min = 1, max = 100) int quantity,
            @ForAll("supportedProfile") String profile) {

        Order order = buildValidatedOrder(unitPrice, quantity);
        Order priced = ENGINE.price(order, profile);

        // grandTotal = subtotal - discountTotal + taxTotal + shippingTotal
        Money expected = priced.getSubtotal()
                .minus(priced.getDiscountTotal())
                .plus(priced.getTaxTotal())
                .plus(priced.getShippingTotal());

        assertEquals(
                0,
                expected.amount().compareTo(priced.getGrandTotal().amount()),
                () -> String.format(
                        "grandTotal invariant violated for profile='%s', unitPrice=%s, qty=%d: "
                        + "expected %s but got %s",
                        profile, unitPrice, quantity,
                        expected.amount(), priced.getGrandTotal().amount()));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Builds a minimal {@link Order} in {@link OrderStatus#VALIDATED} status with one item.
     *
     * @param unitPrice the unit price amount for the single item
     * @param quantity  the item quantity
     * @return a valid order ready to be priced
     */
    private Order buildValidatedOrder(BigDecimal unitPrice, int quantity) {
        Money price = Money.of(unitPrice, USD);
        OrderItem item = new OrderItem(new Sku("SKU-001"), quantity, price);
        return new OrderBuilder()
                .id(new OrderId(UUID.randomUUID()))
                .item(item)
                .status(OrderStatus.VALIDATED)
                .currency(USD)
                .build();
    }
}
