package com.example.orderprocessing.property.pricing;

import com.example.orderprocessing.domain.model.Money;
import com.example.orderprocessing.domain.model.Order;
import com.example.orderprocessing.domain.model.OrderBuilder;
import com.example.orderprocessing.domain.model.OrderId;
import com.example.orderprocessing.domain.model.OrderItem;
import com.example.orderprocessing.domain.model.OrderStatus;
import com.example.orderprocessing.domain.model.Sku;
import com.example.orderprocessing.domain.pricing.PricingEngine;
import com.example.orderprocessing.domain.pricing.PricingStrategyChainFactory;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Property-based tests for pricing non-negativity invariants.
 *
 * <p>Validates that the {@link PricingEngine} always produces non-negative values for
 * subtotal, taxTotal, shippingTotal, and grandTotal for any valid order and supported profile.
 */
class PricingNonNegativityProperties {

    private static final Currency USD = Currency.getInstance("USD");
    private static final PricingEngine ENGINE =
            new PricingEngine(new PricingStrategyChainFactory());

    /**
     * Provides an arbitrary unit price amount between 0.01 and 9999.99 (scale ≤ 2).
     *
     * @return arbitrary {@link BigDecimal} suitable for a unit price
     */
    @Provide
    Arbitrary<BigDecimal> unitPriceAmount() {
        return Arbitraries.bigDecimals()
                .between(new BigDecimal("0.01"), new BigDecimal("9999.99"))
                .ofScale(2);
    }

    /**
     * Provides an arbitrary supported pricing profile name.
     *
     * @return arbitrary over the supported profile names
     */
    @Provide
    Arbitrary<String> supportedProfile() {
        return Arbitraries.of("default", "no-op");
    }

    /**
     * Property 4: subtotal, taxTotal, shippingTotal >= 0 and grandTotal >= 0.
     *
     * <p>For all valid orders and all supported pricing chains, every monetary total
     * produced by the {@link PricingEngine} must be non-negative. This enforces the
     * LSP postcondition on all {@link com.example.orderprocessing.domain.pricing.PricingStrategy}
     * implementations and the overall engine output.
     *
     * <p><b>Validates: Requirements 3.5, 20.1</b>
     *
     * @param unitPrice the unit price amount generated by jqwik
     * @param quantity  the item quantity generated by jqwik
     * @param profile   the pricing profile name generated by jqwik
     */
    @Property
    void allPricingTotalsAreNonNegative(
            @ForAll("unitPriceAmount") BigDecimal unitPrice,
            @ForAll @IntRange(min = 1, max = 100) int quantity,
            @ForAll("supportedProfile") String profile) {

        Order order = buildValidatedOrder(unitPrice, quantity);
        Order priced = ENGINE.price(order, profile);

        assertTrue(
                priced.getSubtotal().isNonNegative(),
                () -> "subtotal must be non-negative, got: " + priced.getSubtotal().amount());

        assertTrue(
                priced.getTaxTotal().isNonNegative(),
                () -> "taxTotal must be non-negative, got: " + priced.getTaxTotal().amount());

        assertTrue(
                priced.getShippingTotal().isNonNegative(),
                () -> "shippingTotal must be non-negative, got: " + priced.getShippingTotal().amount());

        assertTrue(
                priced.getGrandTotal().isNonNegative(),
                () -> "grandTotal must be non-negative, got: " + priced.getGrandTotal().amount());
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Builds a minimal {@link Order} in {@link OrderStatus#VALIDATED} status with one item.
     *
     * @param unitPrice the unit price amount for the single item
     * @param quantity  the item quantity
     * @return a valid order ready to be priced
     */
    private Order buildValidatedOrder(BigDecimal unitPrice, int quantity) {
        Money price = Money.of(unitPrice, USD);
        OrderItem item = new OrderItem(new Sku("SKU-001"), quantity, price);
        return new OrderBuilder()
                .id(new OrderId(UUID.randomUUID()))
                .item(item)
                .status(OrderStatus.VALIDATED)
                .currency(USD)
                .build();
    }
}
