package com.example.orderprocessing.property.cache;

import com.example.orderprocessing.domain.model.Money;
import com.example.orderprocessing.domain.model.Order;
import com.example.orderprocessing.domain.model.OrderBuilder;
import com.example.orderprocessing.domain.model.OrderId;
import com.example.orderprocessing.domain.model.OrderItem;
import com.example.orderprocessing.domain.model.OrderStatus;
import com.example.orderprocessing.domain.model.Sku;
import com.example.orderprocessing.domain.port.OrderCachePort;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Property-based tests for cache-population idempotence (Property 7).
 *
 * <p>Verifies that repeated {@code put(orderId, orderState)} calls with identical state
 * leave the cache observably unchanged — the value retrieved after N puts is the same
 * as after a single put (Requirement 19.1).
 *
 * <p>Uses a simple {@link HashMap}-backed in-memory stub of {@link OrderCachePort} so
 * the test runs without any Spring context or Redis infrastructure.
 */
class CachePopulationIdempotenceProperties {

    private static final Currency USD = Currency.getInstance("USD");

    /**
     * Provides an arbitrary unit price amount between 0.01 and 999.99 (scale ≤ 2).
     *
     * @return arbitrary {@link BigDecimal} suitable for a unit price
     */
    @Provide
    Arbitrary<BigDecimal> unitPriceAmount() {
        return Arbitraries.bigDecimals()
                .between(new BigDecimal("0.01"), new BigDecimal("999.99"))
                .ofScale(2);
    }

    /**
     * Provides an arbitrary repeat count between 2 and 10 for the idempotence check.
     *
     * @return arbitrary int representing how many times put() is called
     */
    @Provide
    Arbitrary<Integer> repeatCount() {
        return Arbitraries.integers().between(2, 10);
    }

    /**
     * Property 7: Repeated {@code put(orderId, orderState)} with identical state leaves
     * the cache observably unchanged.
     *
     * <p>After the first {@code put}, subsequent puts with the same order must not alter
     * the value returned by {@code get}. The cache entry after N puts must be semantically
     * equivalent to the entry after the first put.
     *
     * <p><b>Validates: Requirements 19.1</b>
     *
     * @param unitPrice   the unit price amount generated by jqwik
     * @param quantity    the item quantity generated by jqwik
     * @param repeatCount the number of times put() is called with the same state
     */
    @Property
    void repeatedPutWithIdenticalStateIsIdempotent(
            @ForAll("unitPriceAmount") BigDecimal unitPrice,
            @ForAll @IntRange(min = 1, max = 100) int quantity,
            @ForAll("repeatCount") int repeatCount) {

        InMemoryOrderCache cache = new InMemoryOrderCache();
        Order order = buildOrder(unitPrice, quantity);
        OrderId orderId = order.getId();

        // First put — establishes the baseline
        cache.put(orderId, order);
        Order afterFirstPut = cache.get(orderId).orElseThrow(
                () -> new AssertionError("Cache should contain the order after first put"));

        // Repeated puts with the same order
        for (int i = 1; i < repeatCount; i++) {
            cache.put(orderId, order);
        }

        // The value after N puts must be observably the same as after the first put
        Order afterRepeatedPuts = cache.get(orderId).orElseThrow(
                () -> new AssertionError("Cache should still contain the order after repeated puts"));

        assertEquals(
                afterFirstPut.getId(),
                afterRepeatedPuts.getId(),
                "Order ID must be unchanged after repeated puts");
        assertEquals(
                afterFirstPut.getStatus(),
                afterRepeatedPuts.getStatus(),
                "Order status must be unchanged after repeated puts");
        assertEquals(
                0,
                afterFirstPut.getGrandTotal().amount()
                        .compareTo(afterRepeatedPuts.getGrandTotal().amount()),
                "Grand total must be unchanged after repeated puts");
        assertEquals(
                afterFirstPut.getItems().size(),
                afterRepeatedPuts.getItems().size(),
                "Item count must be unchanged after repeated puts");
    }

    /**
     * Property 7 (variant): After N identical puts, the cache contains exactly one entry
     * for the given order ID — no duplication or corruption occurs.
     *
     * <p><b>Validates: Requirements 19.1</b>
     *
     * @param unitPrice   the unit price amount generated by jqwik
     * @param quantity    the item quantity generated by jqwik
     * @param repeatCount the number of times put() is called with the same state
     */
    @Property
    void repeatedPutDoesNotDuplicateCacheEntries(
            @ForAll("unitPriceAmount") BigDecimal unitPrice,
            @ForAll @IntRange(min = 1, max = 100) int quantity,
            @ForAll("repeatCount") int repeatCount) {

        InMemoryOrderCache cache = new InMemoryOrderCache();
        Order order = buildOrder(unitPrice, quantity);
        OrderId orderId = order.getId();

        for (int i = 0; i < repeatCount; i++) {
            cache.put(orderId, order);
        }

        // Exactly one entry must exist for this order ID
        assertEquals(
                1,
                cache.size(),
                "Cache must contain exactly one entry after " + repeatCount + " identical puts");
        assertTrue(
                cache.get(orderId).isPresent(),
                "Cache must contain the order after repeated puts");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Builds a minimal {@link Order} in {@link OrderStatus#CREATED} status with one item.
     *
     * @param unitPrice the unit price amount for the single item
     * @param quantity  the item quantity
     * @return a valid order
     */
    private Order buildOrder(BigDecimal unitPrice, int quantity) {
        Money price = Money.of(unitPrice, USD);
        OrderItem item = new OrderItem(new Sku("SKU-001"), quantity, price);
        return new OrderBuilder()
                .id(new OrderId(UUID.randomUUID()))
                .item(item)
                .status(OrderStatus.CREATED)
                .currency(USD)
                .build();
    }

    // -------------------------------------------------------------------------
    // In-memory stub
    // -------------------------------------------------------------------------

    /**
     * Simple {@link HashMap}-backed stub of {@link OrderCachePort} used exclusively
     * in property tests. No Spring context or Redis infrastructure is required.
     */
    static final class InMemoryOrderCache implements OrderCachePort {

        private final Map<OrderId, Order> store = new HashMap<>();

        @Override
        public Optional<Order> get(OrderId id) {
            return Optional.ofNullable(store.get(id));
        }

        @Override
        public void put(OrderId id, Order order) {
            // Idempotent: overwriting with the same value is a no-op semantically
            store.put(id, order);
        }

        @Override
        public void evict(OrderId id) {
            store.remove(id);
        }

        @Override
        public boolean isAvailable() {
            return true;
        }

        /** Returns the number of distinct entries currently in the cache. */
        int size() {
            return store.size();
        }
    }
}
