package com.example.orderprocessing.property.lifecycle;

import com.example.orderprocessing.domain.lifecycle.OrderStateMachine;
import com.example.orderprocessing.domain.model.OrderStatus;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Property-based tests for the order lifecycle state machine transition graph.
 *
 * <p>Validates that {@link OrderStateMachine#assertTransition(OrderStatus, OrderStatus)}
 * accepts exactly the edges defined in Requirement 6.1 and rejects all others
 * (Requirements 6.1, 6.2).
 */
class LifecycleTransitionProperties {

    /**
     * The complete set of valid (from → to) transitions as defined by the
     * directed lifecycle graph in Requirement 6.1.
     *
     * <p>CREATED→VALIDATED, CREATED→FAILED, CREATED→CANCELLED
     * VALIDATED→PRICED, VALIDATED→FAILED, VALIDATED→CANCELLED
     * PRICED→RESERVED, PRICED→FAILED, PRICED→CANCELLED
     * RESERVED→CONFIRMED, RESERVED→FAILED, RESERVED→CANCELLED
     * CONFIRMED→SHIPPED, CONFIRMED→CANCELLED
     * SHIPPED→DELIVERED
     */
    private static final Set<String> VALID_TRANSITIONS = Set.of(
            edge(OrderStatus.CREATED,   OrderStatus.VALIDATED),
            edge(OrderStatus.CREATED,   OrderStatus.FAILED),
            edge(OrderStatus.CREATED,   OrderStatus.CANCELLED),
            edge(OrderStatus.VALIDATED, OrderStatus.PRICED),
            edge(OrderStatus.VALIDATED, OrderStatus.FAILED),
            edge(OrderStatus.VALIDATED, OrderStatus.CANCELLED),
            edge(OrderStatus.PRICED,    OrderStatus.RESERVED),
            edge(OrderStatus.PRICED,    OrderStatus.FAILED),
            edge(OrderStatus.PRICED,    OrderStatus.CANCELLED),
            edge(OrderStatus.RESERVED,  OrderStatus.CONFIRMED),
            edge(OrderStatus.RESERVED,  OrderStatus.FAILED),
            edge(OrderStatus.RESERVED,  OrderStatus.CANCELLED),
            edge(OrderStatus.CONFIRMED, OrderStatus.SHIPPED),
            edge(OrderStatus.CONFIRMED, OrderStatus.CANCELLED),
            edge(OrderStatus.SHIPPED,   OrderStatus.DELIVERED)
    );

    /**
     * Encodes a (from, to) pair as a stable string key for set membership tests.
     *
     * @param from the source status
     * @param to   the target status
     * @return a canonical string representation of the directed edge
     */
    private static String edge(OrderStatus from, OrderStatus to) {
        return from.name() + "->" + to.name();
    }

    /**
     * Provides an arbitrary drawn from all {@link OrderStatus} values.
     *
     * @return arbitrary over the full {@code OrderStatus} enum
     */
    @Provide
    Arbitrary<OrderStatus> anyStatus() {
        return Arbitraries.of(OrderStatus.values());
    }

    /**
     * Property 1: Only graph-defined transitions are accepted.
     *
     * <p>For every (from, to) pair drawn from the full {@link OrderStatus} space,
     * {@link OrderStateMachine#assertTransition(OrderStatus, OrderStatus)} must:
     * <ul>
     *   <li>complete without throwing when the pair is an edge in the Req 6.1 graph, and</li>
     *   <li>throw {@link IllegalStateException} when the pair is not an edge in the graph.</li>
     * </ul>
     *
     * <p><b>Validates: Requirements 6.1, 6.2</b>
     *
     * @param from the source status generated by jqwik
     * @param to   the target status generated by jqwik
     */
    @Property
    void onlyGraphDefinedTransitionsAreAccepted(
            @ForAll("anyStatus") OrderStatus from,
            @ForAll("anyStatus") OrderStatus to) {

        boolean isValidEdge = VALID_TRANSITIONS.contains(edge(from, to));

        if (isValidEdge) {
            assertDoesNotThrow(
                    () -> OrderStateMachine.assertTransition(from, to),
                    "assertTransition should accept the valid edge " + from + " -> " + to);
        } else {
            assertThrows(
                    IllegalStateException.class,
                    () -> OrderStateMachine.assertTransition(from, to),
                    "assertTransition should reject the invalid edge " + from + " -> " + to);
        }
    }
}
