package com.example.orderprocessing.property.lifecycle;

import com.example.orderprocessing.domain.lifecycle.OrderStateMachine;
import com.example.orderprocessing.domain.model.OrderStatus;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.Arbitraries;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Property-based tests verifying that no transition is permitted out of any terminal state.
 *
 * <p><b>Validates: Requirements 6.4</b>
 *
 * <p>Property 2: For every terminal status (DELIVERED, CANCELLED, FAILED) and for every
 * possible target status, {@link OrderStateMachine#assertTransition(OrderStatus, OrderStatus)}
 * must throw an exception, because terminal states have no outgoing transitions.
 */
class TerminalStateProperties {

    /**
     * Provides all possible {@link OrderStatus} values as arbitrary inputs for the
     * target-status parameter, covering every conceivable transition attempt.
     *
     * @return an {@link Arbitrary} over all {@link OrderStatus} enum constants
     */
    @Provide
    Arbitrary<OrderStatus> anyStatus() {
        return Arbitraries.of(OrderStatus.values());
    }

    /**
     * Property: no transition out of DELIVERED is ever permitted.
     *
     * <p>For every possible target status, assertTransition(DELIVERED, target) must throw
     * {@link IllegalStateException} because DELIVERED is a terminal state (Requirement 6.4).
     *
     * <p><b>Validates: Requirements 6.4</b>
     *
     * @param target any {@link OrderStatus} generated by jqwik
     */
    @Property
    void noTransitionPermittedFromDelivered(@ForAll("anyStatus") OrderStatus target) {
        assertThatThrownBy(() -> OrderStateMachine.assertTransition(OrderStatus.DELIVERED, target))
                .isInstanceOfAny(IllegalStateException.class, IllegalArgumentException.class)
                .as("Expected an exception when transitioning from terminal state DELIVERED to %s", target);
    }

    /**
     * Property: no transition out of CANCELLED is ever permitted.
     *
     * <p>For every possible target status, assertTransition(CANCELLED, target) must throw
     * {@link IllegalStateException} because CANCELLED is a terminal state (Requirement 6.4).
     *
     * <p><b>Validates: Requirements 6.4</b>
     *
     * @param target any {@link OrderStatus} generated by jqwik
     */
    @Property
    void noTransitionPermittedFromCancelled(@ForAll("anyStatus") OrderStatus target) {
        assertThatThrownBy(() -> OrderStateMachine.assertTransition(OrderStatus.CANCELLED, target))
                .isInstanceOfAny(IllegalStateException.class, IllegalArgumentException.class)
                .as("Expected an exception when transitioning from terminal state CANCELLED to %s", target);
    }

    /**
     * Property: no transition out of FAILED is ever permitted.
     *
     * <p>For every possible target status, assertTransition(FAILED, target) must throw
     * {@link IllegalStateException} because FAILED is a terminal state (Requirement 6.4).
     *
     * <p><b>Validates: Requirements 6.4</b>
     *
     * @param target any {@link OrderStatus} generated by jqwik
     */
    @Property
    void noTransitionPermittedFromFailed(@ForAll("anyStatus") OrderStatus target) {
        assertThatThrownBy(() -> OrderStateMachine.assertTransition(OrderStatus.FAILED, target))
                .isInstanceOfAny(IllegalStateException.class, IllegalArgumentException.class)
                .as("Expected an exception when transitioning from terminal state FAILED to %s", target);
    }
}
